# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "South Brunswick CoderDojo"
title_separator: "|"
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the South Brunswick CoderDojo! Please navigate the website to learn 
  more about us, our goals, our workshop timings, and more!

minimal_mistakes_skin: "contrast"
logo: "/assets/images/sb-coderdojo-logo.png"

repository: "SBDojo/SBDojo.github.io"

# Build settings
markdown: kramdown

# Outputting
timezone: "America/New_York"

# Lunr Search
search: true

# Breadcrumbs
breadcrumbs: true

include:
  - _pages
  - _includes
  - _data

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "CoderDojo Zen"
      icon: "fas fa-yin-yang"
      url: "https://zen.coderdojo.com/dojos/us/south-brunswick-township-nj/south-brunswick-nj-sbpl"
    - label: "Knowledge Base"
      icon: "fa fa-book"
      url: "https://sbdojo.gitbook.io/knowledge-base/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SBDojo"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://instagram.com/sb.coderdojo"

atom_feed:
  hide: true

comments:
  provider: "giscus"
  giscus:
    repo_id              : MDEwOlJlcG9zaXRvcnk0MDI1Mzg0NTA=
    category_name        : Announcements
    category_id          : DIC_kwDOF_4_0s4B-8IU
    discussion_term      : "pathname"
    reactions_enabled    : '1'
    theme                : "light"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
